base = "/" # replace with your full domain name where this collection will be deploy to
ga_measurement_id = ""

[style]
theme = "system-preference" # possible value "system-preference | dark | light"
cover = "center" # posible value "left | center | right"
content = "left" # possible value "left | center | right"

[profile]
name = "Moul"
bio = "A publishing tool for photographers, visual storytellers."

[social]
twitter = ""
github = "moulco/moul"
instagram = "moul.co"
facebook = ""
youtube = ""

[content]
title = "Moul Demo"
tags = ["Photography", "Tool"]
text = """
multi-line text
"""
